### ISSUE TITLE
Using browserSync and apitizer 

### ISSUE THREAD

**Issue by Chandu** [retro/apitizer#8]
I am using browserSync to synchronize my changes on browser during the development.
I am also using apitizer to mock my server side api calls.
However when I enable apitizer browserSync stops working, I guess this is because the XMLHttpRequest is replaced by apitizer.

Is there any way to let apitizer pass through the calls to the url's that are not configured apitizer.fixture.resource?

Or are there any other ways to use browserSync and apitizer together?

**Comment by retro** [comment]
Can you create a repo with the minimal breaking case? It does work with browserSync for me. AFAIK browserSync is using websockets to communicate changes so APItizer shouldn't affect it.

**Comment by Chandu** [comment]
@retro I tried to debug the issue further and the browser sync injects a client script which is using the socket.io.js  (ref@ https://github.com/Automattic/socket.io-client/blob/master/socket.io.js), which in turn is using XmlHttpRequest. I will close this issue for now as am not fully clear which part of browserSync is triggering the Ajax calls. I will reopen it if at all I can find a root cause.
Thanks for your inputs.
