### ISSUE TITLE
Wrap apitizer in nodejs

### ISSUE THREAD

**Issue by zot24** [retro/apitizer#9]
I was wondering if it's possible to wrap `apitizer` into a node app to be able to query the mocked endpoints (that are in a JSONSchema file) from another app we are building in PHP?

Thanks

**Comment by retro** [comment]
I think it should be possible, but it would require some work, especially around the XHR object. That said, it shouldn't be too hard as the browser - only code is contained in the https://github.com/retro/apitizer/blob/master/lib/fixtures.js file.

I'm not sure I'll be able to work on that anytime soon, but I could provide you with some help if you want to work on that

**Comment by zot24** [comment]
We have decide not to implement the feature we need at the minute so I guess we won't be using Apitizer at least for now. Thanks you so much for your answer!
